#%RAML 1.0 NamedExample
records_in_the_table:
-
  -OrderID: "O-010"
  -CustomerName : "om"
  -OrderStatus : "Received"
  -OrderStartDate: 12-02-2021
  -OrderEndDate: 02-03-2021
  -Qty: 4  
  -Order_amt: 32452.32
-
  -OrderID: "O-014"
  -CustomerName : "Rohit"
  -OrderStatus : "Received"
  -OrderStartDate: 14-12-2020
  -OrderEndDate: 22-12-2020
  -Qty: 6  
  -Order_amt: 84364.34