https:
  port: "8091"
  port1: "8092"
  baseUrl: "/api"
  host: "mysql-sapi-api.us-e2.cloudhub.io"
  
jms:
  vhost: "zxtxqpox"
  port: "5671"
  host: "puffin.rmq2.cloudamqp.com"
  
req:
  host: "datawarehouse-sapi.us-e2.cloudhub.io"
  basePath: "/api"
  