http:
  port: "8081"
  
american:
  host: "training4-american-api-naik.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "0bde551744744dd2a1f0595410a5d538"
  client_secret: "Bb81fCA4bC4f4b8bA940Db80714877Bc"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"